### ISSUE TITLE
Need to update notify service redoc with correct syntax for python code

### ISSUE THREAD

**Issue by rujutashinde** [waynesun09/notify-service#23]
Currently for all examples the syntax for python shows to use the following

`import http.client

conn = http.client.HTTPConnection("undefinedundefined")
`
It should be 
`import http.client

conn = http.client.HTTPSConnection("server_url")
`
Using HTTPConnection throws a 302 error

**Comment by waynesun09** [comment]
HTTPConnection or HTTPSConnection is decided by 

https://github.com/Kong/httpsnippet/blob/71eec07c833c6421270c417a9d6e311b0fb34f27/src/targets/python/python3.js#L22
`  const protocol = source.uriObj.protocol
  if (protocol === 'https:') {
    code.push('conn = http.client.HTTPSConnection("%s")', source.uriObj.host)
      .blank()
  } else {
    code.push('conn = http.client.HTTPConnection("%s")', source.uriObj.host)
      .blank()
  }`

which check current host uri when the app been started.

while in the helm OCP deploy, by default the app tls is not enabled. And with OCP route use tls redirection, the url shows as https. But inside the app when run the code snip script it still will be recognized as tls not enabled.

To fix this and also the url undefined issue, need remove run the code snip generate from the backend and update redoc script on frontend.

**Comment by rujutashinde** [comment]
Does that mean similar logic will need to be applied on the teflo plugin side? Or we will have the D&O's notify service always resolved to https

**Comment by waynesun09** [comment]
With current helm deploy as default, it will be https, and you could found the clue in the URL when you open Swagger UI or Redoc.

**Comment by waynesun09** [comment]
The server url issue is resolved.
