### ISSUE TITLE
Need to update teflo_scenario_email template

### ISSUE THREAD

**Issue by rujutashinde** [waynesun09/notify-service#25]
The current teflo_Scenario_email template is missing some information
Following should be modified

https://github.com/waynesun09/notify-service/blob/main/app/templates/build/teflo_scenario_email.html#L221 > failed tasks is not printed instead passed tasks is preinted again

https://github.com/waynesun09/notify-service/blob/main/app/templates/build/teflo_scenario_email.html#L202-L208 > subject is not a part of body, so it is not getting printed

the scenario name needs to be added {{ scenario.name }}

https://github.com/waynesun09/notify-service/blob/main/app/templates/build/teflo_scenario_email.html#L224-L231  the logic to derive executes does not work. 
It should be similar to what is present in the gchat template

Also need to add details for scenario.reports

**Comment by waynesun09** [comment]
> The current teflo_Scenario_email template is missing some information
> Following should be modified
> 
> https://github.com/waynesun09/notify-service/blob/main/app/templates/build/teflo_scenario_email.html#L221 > failed tasks is not printed instead passed tasks is preinted again

Yeah, that's a typo.


> 
> https://github.com/waynesun09/notify-service/blob/main/app/templates/build/teflo_scenario_email.html#L202-L208 > subject is not a part of body, so it is not getting printed
> 
> the scenario name needs to be added {{ scenario.name }}
> 

subject is printed in the email body, do you want to remove it and replace with scenario.name ?

> https://github.com/waynesun09/notify-service/blob/main/app/templates/build/teflo_scenario_email.html#L224-L231 the logic to derive executes does not work.
> It should be similar to what is present in the gchat template

It works when it's provided.

> 
> Also need to add details for scenario.reports

The scenario.reports also works when provided.

Could you provide the message body which you didn't get the executes and report generated in the email?

**Comment by rujutashinde** [comment]
> > The current teflo_Scenario_email template is missing some information
> > Following should be modified
> > https://github.com/waynesun09/notify-service/blob/main/app/templates/build/teflo_scenario_email.html#L221 > failed tasks is not printed instead passed tasks is preinted again
> 
> Yeah, that's a typo and fixed.
> 
**[rushinde] OK**

> > https://github.com/waynesun09/notify-service/blob/main/app/templates/build/teflo_scenario_email.html#L202-L208 > subject is not a part of body, so it is not getting printed
> > the scenario name needs to be added {{ scenario.name }}
> 
> subject is printed in the email body, do you want to remove it and replace with scenario.name ?
> 
**[rushinde] The subject is printed correctly. Nothing needs to change there. Sorry i did not see that in the email properly
What needs to be added is Scenario Name: {{scenario.name}} as a row in the email template. right now the first line that gets printed is overall status**

> > https://github.com/waynesun09/notify-service/blob/main/app/templates/build/teflo_scenario_email.html#L224-L231 the logic to derive executes does not work.
> > It should be similar to what is present in the gchat template
> 
> It works when it's provided.

**[rushinde] . You are correct. Only thing that needs to change here is the following, where Execute Task Testrun Results is printed before checking the if condition

`<div style="font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:16px;font-weight:400;line-height:24px;text-align:left;color:#637381;">Execute Task Testrun Results:{% if scenario.executes %}{% for execute in scenario.executes %}</div>`

to this

`<div style="font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:16px;font-weight:400;line-height:24px;text-align:left;color:#637381;">{% if scenario.executes %}{% for execute in scenario.executes %}Execute Task Testrun Results:</div>`**

> > Also need to add details for scenario.reports
> 
> The scenario.reports also works when provided.
**[rushinde] you are correct nothing needs to change here. I somehow missed the scenario.reports when i was searching teh template**

> Could you provide the message body which you didn't get the executes and report generated in the email?

**Comment by waynesun09** [comment]
Updated and raised PR:

https://github.com/waynesun09/notify-service/pull/26

**Comment by waynesun09** [comment]
This is resolved.
